version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into amazon ecr
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 196236753581.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building docker images
      - docker build -t  web:1 .
      - docker tag web:1 196236753581.dkr.ecr.us-east-1.amazonaws.com/soban-ecs:latest
      - docker tag web:1 196236753581.dkr.ecr.us-east-1.amazonaws.com/soban-ecs:$CODEBUILD_BUILD_NUMBER
      - docker images 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushind docker images
      - docker push 196236753581.dkr.ecr.us-east-1.amazonaws.com/soban-ecs:latest
      - docker push 196236753581.dkr.ecr.us-east-1.amazonaws.com/soban-ecs:$CODEBUILD_BUILD_NUMBER

